services:
  chat-app-frontend:
    container_name: chat-app-frontend
    build:
      context: .
      dockerfile: dockerfile
    image: chat-app-frontend:latest
    ports:
      - '7979:80'
    volumes:
      - ./env.js:/app/public/env-config.js
