services:
  frontend-dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - ./env.js:/app/public/env-config.js
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    command: npm run dev
