export const SOCKET_EVENTS = {
  GET_ONLINE_USERS: 'GET_ONLINE_USERS',
  SEND_MESSAGE: 'SEND_MESSAGE',
  HAS_NEW_MESSAGE: 'HAS_NEW_MESSAGE',
  UPDATE_FRIEND_LIST: 'UPDATE_FRIEND_LIST',
  CLOSE_CONNECTION: 'CLOSE_CONNECTION',
  GET_FRIEND_LIST: 'GET_FRIEND_LIST',
  HAS_NEW_NOTIFICATION: 'HAS_NEW_NOTIFICATION',
}
